/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -Ic:\Nim\lib -o c:\users\202378\documents\github\spacebarrace\src\nimcache\csfml_csfml_graphics.o c:\users\202378\documents\github\spacebarrace\src\nimcache\csfml_csfml_graphics.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct Color109438 Color109438;
typedef struct Transform109665 Transform109665;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct Blendmode109430 Blendmode109430;
typedef struct Currenttexturetype112026 Currenttexturetype112026;
typedef struct TY112096 TY112096;
typedef struct RenderwindowHEX3Aobjecttype109634 RenderwindowHEX3Aobjecttype109634;
typedef struct Videomode107919 Videomode107919;
typedef struct Contextsettings107943 Contextsettings107943;
typedef struct TY105018 TY105018;
typedef struct FontHEX3Aobjecttype109614 FontHEX3Aobjecttype109614;
typedef struct TextHEX3Aobjecttype109646 TextHEX3Aobjecttype109646;
typedef struct Vector2i106084 Vector2i106084;
typedef struct Event107892 Event107892;
typedef struct Renderstates110263 Renderstates110263;
typedef struct TextureHEX3Aobjecttype109650 TextureHEX3Aobjecttype109650;
typedef struct ShaderHEX3Aobjecttype109622 ShaderHEX3Aobjecttype109622;
typedef struct Keyevent107841 Keyevent107841;
typedef struct Mousebuttonevent107855 Mousebuttonevent107855;
typedef struct Textevent107848 Textevent107848;
typedef struct Joystickconnectevent107874 Joystickconnectevent107874;
typedef struct Joystickmoveevent107865 Joystickmoveevent107865;
typedef struct Joystickbuttonevent107870 Joystickbuttonevent107870;
typedef struct Sizeevent107877 Sizeevent107877;
typedef struct Mousemoveevent107851 Mousemoveevent107851;
typedef struct Mousewheelevent107860 Mousewheelevent107860;
struct  Color109438  {
NU8 r;
NU8 g;
NU8 b;
NU8 a;
};
typedef float TY109666[9];
struct  Transform109665  {
TY109666 matrix;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(Transform109665, TY109670) (float a00, float a01, float a02, float a10, float a11, float a12, float a20, float a21, float a22);
struct  Blendmode109430  {
NI32 colorsrcfactor;
NI32 colordstfactor;
NI32 colorequation;
NI32 alphasrcfactor;
NI32 alphadstfactor;
NI32 alphaequation;
};
struct  Currenttexturetype112026  {
char dummy;
};
struct  Videomode107919  {
int width;
int height;
int bitsperpixel;
};
struct  Contextsettings107943  {
int depthbits;
int stencilbits;
int antialiasinglevel;
int majorversion;
int minorversion;
};
typedef N_CDECL_PTR(RenderwindowHEX3Aobjecttype109634*, TY110293) (Videomode107919 mode, NU32* title, NU32 style, Contextsettings107943* settings);
typedef N_CDECL_PTR(FontHEX3Aobjecttype109614*, TY110022) (NCSTRING filename);
typedef N_CDECL_PTR(TextHEX3Aobjecttype109646*, TY111087) (void);
typedef N_CDECL_PTR(void, TY111145) (TextHEX3Aobjecttype109646* text, NU32* str);
typedef N_CDECL_PTR(void, TY111149) (TextHEX3Aobjecttype109646* text, FontHEX3Aobjecttype109614* font);
typedef N_CDECL_PTR(void, TY111153) (TextHEX3Aobjecttype109646* text, int size);
typedef N_CDECL_PTR(void, TY111161) (TextHEX3Aobjecttype109646* text, Color109438 color);
typedef N_CDECL_PTR(int, TY110333) (RenderwindowHEX3Aobjecttype109634* renderwindow);
typedef N_CDECL_PTR(void, TY110418) (RenderwindowHEX3Aobjecttype109634* renderwindow, Color109438 color);
struct  Vector2i106084  {
int x;
int y;
};
typedef N_CDECL_PTR(Vector2i106084, TY110592) (RenderwindowHEX3Aobjecttype109634* relativeto);
typedef N_CDECL_PTR(int, TY110339) (RenderwindowHEX3Aobjecttype109634* renderwindow, Event107892* event);
typedef N_CDECL_PTR(void, TY110330) (RenderwindowHEX3Aobjecttype109634* renderwindow);
struct  Renderstates110263  {
Blendmode109430 blendmode;
Transform109665 transform;
TextureHEX3Aobjecttype109650* texture;
ShaderHEX3Aobjecttype109622* shader;
};
typedef N_CDECL_PTR(void, TY110462) (RenderwindowHEX3Aobjecttype109634* renderwindow, TextHEX3Aobjecttype109646* obj, Renderstates110263* states);
typedef N_CDECL_PTR(void, TY110404) (RenderwindowHEX3Aobjecttype109634* renderwindow);
typedef N_CDECL_PTR(void, TY111092) (TextHEX3Aobjecttype109646* text);
struct  RenderwindowHEX3Aobjecttype109634  {
char dummy;
};
struct  FontHEX3Aobjecttype109614  {
char dummy;
};
struct  TextHEX3Aobjecttype109646  {
char dummy;
};
struct  Keyevent107841  {
NI32 code;
int alt;
int control;
int shift;
int system;
};
struct  Mousebuttonevent107855  {
NI32 button;
int x;
int y;
};
struct  Textevent107848  {
NU32 unicode;
};
struct  Joystickconnectevent107874  {
int joystickid;
};
struct  Joystickmoveevent107865  {
int joystickid;
NI32 axis;
float position;
};
struct  Joystickbuttonevent107870  {
int joystickid;
int button;
};
struct  Sizeevent107877  {
int width;
int height;
};
struct  Mousemoveevent107851  {
int x;
int y;
};
struct  Mousewheelevent107860  {
int delta;
int x;
int y;
};
struct  Event107892  {
NI32 kind;
union{
struct {Keyevent107841 key;
} S1;
struct {Mousebuttonevent107855 mousebutton;
} S2;
struct {Textevent107848 text;
} S3;
struct {Joystickconnectevent107874 joystickconnect;
} S4;
struct {Joystickmoveevent107865 joystickmove;
} S5;
struct {Joystickbuttonevent107870 joystickbutton;
} S6;
struct {Sizeevent107877 size;
} S7;
struct {Mousemoveevent107851 mousemove;
} S8;
struct {Mousewheelevent107860 mousewheel;
} S9;
} kindU;
};
struct  TextureHEX3Aobjecttype109650  {
char dummy;
};
struct  ShaderHEX3Aobjecttype109622  {
char dummy;
};
struct TY112096 {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
struct TY105018 {
  TGenericSeq Sup;
  NU32 data[SEQ_DECL_SIZE];
};
N_NIMCALL(Color109438, color_111473)(NI red, NI green, NI blue, NI alpha);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(Transform109665, transform_111790)(void);
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
N_NIMCALL(Blendmode109430, blendmode_111925)(NI32 colorsourcefactor, NI32 colordestinationfactor, NI32 colorblendequation, NI32 alphasourcefactor, NI32 alphadestinationfactor, NI32 alphablendequation);
N_NIMCALL(Blendmode109430, blendmode_111940)(NI32 sourcefactor, NI32 destinationfactor, NI32 blendequation);
N_NIMCALL(TY112096*, newseq_112091)(NI len);
N_NIMCALL(TY105018*, utf8to32_105015)(NimStringDesc* s);
N_NIMCALL(RenderwindowHEX3Aobjecttype109634*, newrenderwindowu32_110299)(Videomode107919 mode, NU32* title, NU32 style, Contextsettings107943 settings);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, strHEX3D_112169)(TextHEX3Aobjecttype109646* text, NimStringDesc* str);
N_NIMCALL(void, drawtext_110467)(RenderwindowHEX3Aobjecttype109634* renderwindow, TextHEX3Aobjecttype109646* obj, Renderstates110263 states);
STRING_LITERAL(TMP179, "csfml-graphics-2.dll", 20);
STRING_LITERAL(TMP180, "csfml-graphics-2.dll", 20);
Color109438 Black_111639;
extern TFrame* frameptr_17042;
Color109438 White_111643;
Color109438 Red_111645;
Color109438 Green_111647;
Color109438 Blue_111649;
Color109438 Yellow_111652;
Color109438 Magenta_111655;
Color109438 Cyan_111658;
Color109438 Transparent_111659;
Transform109665 Identity_111808;
static void* TMP178;
TY109670 Dl_109669;
Blendmode109430 Blendalpha_111959;
Blendmode109430 Blendadd_111972;
Blendmode109430 Blendmultiply_111981;
Blendmode109430 Blendnone_111993;
Currenttexturetype112026 Currenttexture_112030;
TY110293 Dl_110292;
TY110022 Dl_110021;
TY111087 Dl_111086;
TY111145 Dl_111144;
TY111149 Dl_111148;
TY111153 Dl_111152;
TY111161 Dl_111160;
TY110333 Dl_110332;
TY110418 Dl_110417;
TY110592 Dl_110591;
TY110339 Dl_110338;
TY110330 Dl_110329;
TY110462 Dl_110461;
TY110404 Dl_110403;
TY111092 Dl_111091;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(Color109438, color_111473)(NI red, NI green, NI blue, NI alpha) {
	Color109438 result;
	nimfr("color", "csfml_graphics.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(43, "csfml_graphics.nim");
	result.r = ((NU8) (red));
	nimln(44, "csfml_graphics.nim");
	result.g = ((NU8) (green));
	nimln(45, "csfml_graphics.nim");
	result.b = ((NU8) (blue));
	nimln(46, "csfml_graphics.nim");
	result.a = ((NU8) (alpha));
	popFrame();
	return result;
}

N_NIMCALL(Transform109665, transform_111790)(void) {
	Transform109665 result;
	nimfr("transform", "csfml_graphics.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(117, "csfml_graphics.nim");
	nimln(118, "csfml_graphics.nim");
	result = Dl_109669(1.0000000000000000e+000, 0.0, 0.0, 0.0, 1.0000000000000000e+000, 0.0, 0.0, 0.0, 1.0000000000000000e+000);
	popFrame();
	return result;
}

N_NIMCALL(Blendmode109430, blendmode_111925)(NI32 colorsourcefactor, NI32 colordestinationfactor, NI32 colorblendequation, NI32 alphasourcefactor, NI32 alphadestinationfactor, NI32 alphablendequation) {
	Blendmode109430 result;
	nimfr("blendMode", "csfml_graphics.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(164, "csfml_graphics.nim");
	result.colorsrcfactor = colorsourcefactor;
	nimln(165, "csfml_graphics.nim");
	result.colordstfactor = colordestinationfactor;
	nimln(166, "csfml_graphics.nim");
	result.colorequation = colorblendequation;
	nimln(167, "csfml_graphics.nim");
	result.alphasrcfactor = alphasourcefactor;
	nimln(168, "csfml_graphics.nim");
	result.alphadstfactor = alphadestinationfactor;
	nimln(169, "csfml_graphics.nim");
	result.alphaequation = alphablendequation;
	popFrame();
	return result;
}

N_NIMCALL(Blendmode109430, blendmode_111940)(NI32 sourcefactor, NI32 destinationfactor, NI32 blendequation) {
	Blendmode109430 result;
	nimfr("blendMode", "csfml_graphics.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(172, "csfml_graphics.nim");
	nimln(181, "csfml_graphics.nim");
	result = blendmode_111925(sourcefactor, destinationfactor, blendequation, sourcefactor, destinationfactor, blendequation);
	popFrame();
	return result;
}

N_NIMCALL(RenderwindowHEX3Aobjecttype109634*, newrenderwindowu32_110299)(Videomode107919 mode, NU32* title, NU32 style, Contextsettings107943 settings) {
	RenderwindowHEX3Aobjecttype109634* result;
	Contextsettings107943 Csettings;
	nimfr("newRenderWindow_U32", "csfml_graphics_gen.nim")
	result = 0;
	nimln(1816, "csfml_graphics_gen.nim");
	nimln(1823, "csfml_graphics_gen.nim");
	Csettings = settings;
	nimln(1824, "csfml_graphics_gen.nim");
	result = Dl_110292(mode, title, style, (&Csettings));
	popFrame();
	return result;
}

N_NIMCALL(RenderwindowHEX3Aobjecttype109634*, newrenderwindow_112058)(Videomode107919 mode, NimStringDesc* title, NU32 style, Contextsettings107943 settings) {
	RenderwindowHEX3Aobjecttype109634* result;
	TY105018* t;
	nimfr("newRenderWindow", "csfml_graphics.nim")
	result = 0;
	nimln(237, "csfml_graphics.nim");
	nimln(244, "csfml_graphics.nim");
	t = utf8to32_105015(title);
	nimln(245, "csfml_graphics.nim");
	if ((NU)(((NI) 0)) >= (NU)(t->Sup.len)) raiseIndexError();
	result = newrenderwindowu32_110299(mode, (&t->data[((NI) 0)]), style, settings);
	popFrame();
	return result;
}

N_NIMCALL(void, strHEX3D_112169)(TextHEX3Aobjecttype109646* text, NimStringDesc* str) {
	TY105018* t;
	nimfr("str=", "csfml_graphics.nim")
	nimln(270, "csfml_graphics.nim");
	t = utf8to32_105015(str);
	nimln(271, "csfml_graphics.nim");
	if ((NU)(((NI) 0)) >= (NU)(t->Sup.len)) raiseIndexError();
	Dl_111144(text, (&t->data[((NI) 0)]));
	popFrame();
}

N_NIMCALL(TextHEX3Aobjecttype109646*, newtext_112474)(NimStringDesc* str, FontHEX3Aobjecttype109614* font, NI charactersize) {
	TextHEX3Aobjecttype109646* result;
	nimfr("newText", "csfml_graphics.nim")
{	result = 0;
	nimln(381, "csfml_graphics.nim");
	result = Dl_111086();
	nimln(382, "csfml_graphics.nim");
	{
		if (!(result == NIM_NIL)) goto LA3;
		result = NIM_NIL;
		goto BeforeRet;
	}
	LA3: ;
	nimln(383, "csfml_graphics.nim");
	strHEX3D_112169(result, str);
	nimln(384, "csfml_graphics.nim");
	Dl_111148(result, font);
	nimln(385, "csfml_graphics.nim");
	Dl_111152(result, ((int) (charactersize)));
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, drawtext_110467)(RenderwindowHEX3Aobjecttype109634* renderwindow, TextHEX3Aobjecttype109646* obj, Renderstates110263 states) {
	Renderstates110263 Cstates;
	nimfr("drawText", "csfml_graphics_gen.nim")
	nimln(2160, "csfml_graphics_gen.nim");
	Cstates = states;
	nimln(2161, "csfml_graphics_gen.nim");
	Dl_110461(renderwindow, obj, (&Cstates));
	popFrame();
}

N_NIMCALL(void, draw_138106)(RenderwindowHEX3Aobjecttype109634* rendertarget, TextHEX3Aobjecttype109646* obj, Renderstates110263 states) {
	nimfr("draw", "csfml_graphics.nim")
	nimln(282, "csfml_graphics.nim");
	drawtext_110467(rendertarget, obj, states);
	popFrame();
}

N_NIMCALL(Renderstates110263, renderstates_112012)(Blendmode109430 blendmode, Transform109665 transform, TextureHEX3Aobjecttype109650* texture, ShaderHEX3Aobjecttype109622* shader) {
	Renderstates110263 result;
	nimfr("renderStates", "csfml_graphics.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(198, "csfml_graphics.nim");
	result.blendmode = blendmode;
	nimln(199, "csfml_graphics.nim");
	result.transform = transform;
	nimln(200, "csfml_graphics.nim");
	result.texture = texture;
	nimln(201, "csfml_graphics.nim");
	result.shader = shader;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, csfml_csfml_graphicsInit)(void) {
	Currenttexturetype112026 LOC1;
	nimfr("csfml_graphics", "csfml_graphics.nim")
	nimln(74, "csfml_graphics.nim");
	Black_111639 = color_111473(((NI) 0), ((NI) 0), ((NI) 0), ((NI) 255));
	nimln(75, "csfml_graphics.nim");
	White_111643 = color_111473(((NI) 255), ((NI) 255), ((NI) 255), ((NI) 255));
	nimln(76, "csfml_graphics.nim");
	Red_111645 = color_111473(((NI) 255), ((NI) 0), ((NI) 0), ((NI) 255));
	nimln(77, "csfml_graphics.nim");
	Green_111647 = color_111473(((NI) 0), ((NI) 255), ((NI) 0), ((NI) 255));
	nimln(78, "csfml_graphics.nim");
	Blue_111649 = color_111473(((NI) 0), ((NI) 0), ((NI) 255), ((NI) 255));
	nimln(79, "csfml_graphics.nim");
	Yellow_111652 = color_111473(((NI) 255), ((NI) 255), ((NI) 0), ((NI) 255));
	nimln(80, "csfml_graphics.nim");
	Magenta_111655 = color_111473(((NI) 255), ((NI) 0), ((NI) 255), ((NI) 255));
	nimln(81, "csfml_graphics.nim");
	Cyan_111658 = color_111473(((NI) 0), ((NI) 255), ((NI) 255), ((NI) 255));
	nimln(82, "csfml_graphics.nim");
	Transparent_111659 = color_111473(((NI) 0), ((NI) 0), ((NI) 0), ((NI) 0));
	nimln(119, "csfml_graphics.nim");
	Identity_111808 = transform_111790();
	nimln(183, "csfml_graphics.nim");
	Blendalpha_111959 = blendmode_111925(((NI32) 6), ((NI32) 7), ((NI32) 0), ((NI32) 1), ((NI32) 7), ((NI32) 0));
	nimln(185, "csfml_graphics.nim");
	Blendadd_111972 = blendmode_111925(((NI32) 6), ((NI32) 1), ((NI32) 0), ((NI32) 1), ((NI32) 1), ((NI32) 0));
	nimln(187, "csfml_graphics.nim");
	Blendmultiply_111981 = blendmode_111940(((NI32) 4), ((NI32) 0), ((NI32) 0));
	nimln(188, "csfml_graphics.nim");
	Blendnone_111993 = blendmode_111940(((NI32) 1), ((NI32) 0), ((NI32) 0));
	nimln(206, "csfml_graphics.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	Currenttexture_112030 = LOC1;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, csfml_csfml_graphicsDatInit)(void) {
if (!((TMP178 = nimLoadLibrary((NimStringDesc*) &TMP179))
)) nimLoadLibraryError((NimStringDesc*) &TMP180);
	Dl_109669 = (TY109670) nimGetProcAddr(TMP178, "sfTransform_fromMatrix");
	Dl_110292 = (TY110293) nimGetProcAddr(TMP178, "sfRenderWindow_createUnicode");
	Dl_110021 = (TY110022) nimGetProcAddr(TMP178, "sfFont_createFromFile");
	Dl_111086 = (TY111087) nimGetProcAddr(TMP178, "sfText_create");
	Dl_111144 = (TY111145) nimGetProcAddr(TMP178, "sfText_setUnicodeString");
	Dl_111148 = (TY111149) nimGetProcAddr(TMP178, "sfText_setFont");
	Dl_111152 = (TY111153) nimGetProcAddr(TMP178, "sfText_setCharacterSize");
	Dl_111160 = (TY111161) nimGetProcAddr(TMP178, "sfText_setColor");
	Dl_110332 = (TY110333) nimGetProcAddr(TMP178, "sfRenderWindow_isOpen");
	Dl_110417 = (TY110418) nimGetProcAddr(TMP178, "sfRenderWindow_clear");
	Dl_110591 = (TY110592) nimGetProcAddr(TMP178, "sfMouse_getPositionRenderWindow");
	Dl_110338 = (TY110339) nimGetProcAddr(TMP178, "sfRenderWindow_pollEvent");
	Dl_110329 = (TY110330) nimGetProcAddr(TMP178, "sfRenderWindow_close");
	Dl_110461 = (TY110462) nimGetProcAddr(TMP178, "sfRenderWindow_drawText");
	Dl_110403 = (TY110404) nimGetProcAddr(TMP178, "sfRenderWindow_display");
	Dl_111091 = (TY111092) nimGetProcAddr(TMP178, "sfText_destroy");
}

