/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -Ic:\Nim\lib -o c:\users\202378\documents\github\spacebarrace\src\nimcache\csfml_csfml_util.o c:\users\202378\documents\github\spacebarrace\src\nimcache\csfml_csfml_util.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct TY105018 TY105018;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TY105018 {
  TGenericSeq Sup;
  NU32 data[SEQ_DECL_SIZE];
};
N_NIMCALL(TY105018*, utf8to32_105015)(NimStringDesc* s);
N_NIMCALL(void, TMP149)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NIM_BOOL, tobool_105085)(int x);
N_NIMCALL(int, toboolint_105096)(NIM_BOOL x);
N_NIMCALL(NU32, HEX7C_105107)(NU32 a, NU32 b);
N_NIMCALL(NU32, toruneu32_105130)(NI x);
N_NIMCALL(NI, torune_105140)(NU32 x);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
extern TNimType NTI124; /* uint32 */
TNimType NTI105018; /* seq[RuneU32] */
extern TFrame* frameptr_17042;
N_NIMCALL(void, TMP149)(void* p, NI op) {
	TY105018* a;
	NI LOC1;
	a = (TY105018*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(TY105018*, utf8to32_105015)(NimStringDesc* s) {
	TY105018* result;
	nimfr("utf8to32", "csfml_util.nim")
	result = 0;
	nimln(34, "csfml_util.nim");
	result = (TY105018*) newSeq((&NTI105018), 0);
	{
		NI c_105036;
		NI i_105060;
		NI result_105062;
		c_105036 = 0;
		nimln(1250, "unicode.nim");
		i_105060 = ((NI) 0);
		result_105062 = 0;
		{
			nimln(1252, "unicode.nim");
			while (1) {
				if (!(i_105060 < (s ? s->Sup.len : 0))) goto LA3;
				nimln(56, "unicode.nim");
				{
					NI TMP150;
					if ((NU)(i_105060) > (NU)(s->Sup.len)) raiseIndexError();
					if (!((NU32)(((NI) (((NU8)(s->data[i_105060]))))) <= (NU32)(((NI) 127)))) goto LA6;
					nimln(57, "unicode.nim");
					if ((NU)(i_105060) > (NU)(s->Sup.len)) raiseIndexError();
					result_105062 = ((NI) (((NU8)(s->data[i_105060]))));
					nimln(58, "unicode.nim");
					TMP150 = addInt(i_105060, ((NI) 1));
					i_105060 = (NI)(TMP150);
				}
				goto LA4;
				LA6: ;
				{
					NI TMP151;
					NI TMP152;
					nimln(59, "unicode.nim");
					if ((NU)(i_105060) > (NU)(s->Sup.len)) raiseIndexError();
					if (!((NI)((NU32)(((NI) (((NU8)(s->data[i_105060]))))) >> (NU32)(((NI) 5))) == ((NI) 6))) goto LA9;
					nimln(61, "unicode.nim");
					if ((NU)(i_105060) > (NU)(s->Sup.len)) raiseIndexError();
					nimln(62, "unicode.nim");
					TMP151 = addInt(i_105060, ((NI) 1));
					if ((NU)((NI)(TMP151)) > (NU)(s->Sup.len)) raiseIndexError();
					result_105062 = (NI)((NI)((NU32)(((NI) ((NI)(((NI) (((NU8)(s->data[i_105060])))) & ((NI) 31))))) << (NU32)(((NI) 6))) | ((NI) ((NI)(((NI) (((NU8)(s->data[(NI)(TMP151)])))) & ((NI) 63)))));
					nimln(63, "unicode.nim");
					TMP152 = addInt(i_105060, ((NI) 2));
					i_105060 = (NI)(TMP152);
				}
				goto LA4;
				LA9: ;
				{
					NI TMP153;
					NI TMP154;
					NI TMP155;
					nimln(64, "unicode.nim");
					if ((NU)(i_105060) > (NU)(s->Sup.len)) raiseIndexError();
					if (!((NI)((NU32)(((NI) (((NU8)(s->data[i_105060]))))) >> (NU32)(((NI) 4))) == ((NI) 14))) goto LA12;
					nimln(67, "unicode.nim");
					nimln(68, "unicode.nim");
					nimln(67, "unicode.nim");
					if ((NU)(i_105060) > (NU)(s->Sup.len)) raiseIndexError();
					nimln(68, "unicode.nim");
					TMP153 = addInt(i_105060, ((NI) 1));
					if ((NU)((NI)(TMP153)) > (NU)(s->Sup.len)) raiseIndexError();
					nimln(69, "unicode.nim");
					TMP154 = addInt(i_105060, ((NI) 2));
					if ((NU)((NI)(TMP154)) > (NU)(s->Sup.len)) raiseIndexError();
					result_105062 = (NI)((NI)((NI)((NU32)(((NI) ((NI)(((NI) (((NU8)(s->data[i_105060])))) & ((NI) 15))))) << (NU32)(((NI) 12))) | (NI)((NU32)(((NI) ((NI)(((NI) (((NU8)(s->data[(NI)(TMP153)])))) & ((NI) 63))))) << (NU32)(((NI) 6)))) | ((NI) ((NI)(((NI) (((NU8)(s->data[(NI)(TMP154)])))) & ((NI) 63)))));
					nimln(70, "unicode.nim");
					TMP155 = addInt(i_105060, ((NI) 3));
					i_105060 = (NI)(TMP155);
				}
				goto LA4;
				LA12: ;
				{
					NI TMP156;
					NI TMP157;
					NI TMP158;
					NI TMP159;
					nimln(71, "unicode.nim");
					if ((NU)(i_105060) > (NU)(s->Sup.len)) raiseIndexError();
					if (!((NI)((NU32)(((NI) (((NU8)(s->data[i_105060]))))) >> (NU32)(((NI) 3))) == ((NI) 30))) goto LA15;
					nimln(75, "unicode.nim");
					nimln(77, "unicode.nim");
					nimln(76, "unicode.nim");
					nimln(75, "unicode.nim");
					if ((NU)(i_105060) > (NU)(s->Sup.len)) raiseIndexError();
					nimln(76, "unicode.nim");
					TMP156 = addInt(i_105060, ((NI) 1));
					if ((NU)((NI)(TMP156)) > (NU)(s->Sup.len)) raiseIndexError();
					nimln(77, "unicode.nim");
					TMP157 = addInt(i_105060, ((NI) 2));
					if ((NU)((NI)(TMP157)) > (NU)(s->Sup.len)) raiseIndexError();
					nimln(78, "unicode.nim");
					TMP158 = addInt(i_105060, ((NI) 3));
					if ((NU)((NI)(TMP158)) > (NU)(s->Sup.len)) raiseIndexError();
					result_105062 = (NI)((NI)((NI)((NI)((NU32)(((NI) ((NI)(((NI) (((NU8)(s->data[i_105060])))) & ((NI) 7))))) << (NU32)(((NI) 18))) | (NI)((NU32)(((NI) ((NI)(((NI) (((NU8)(s->data[(NI)(TMP156)])))) & ((NI) 63))))) << (NU32)(((NI) 12)))) | (NI)((NU32)(((NI) ((NI)(((NI) (((NU8)(s->data[(NI)(TMP157)])))) & ((NI) 63))))) << (NU32)(((NI) 6)))) | ((NI) ((NI)(((NI) (((NU8)(s->data[(NI)(TMP158)])))) & ((NI) 63)))));
					nimln(79, "unicode.nim");
					TMP159 = addInt(i_105060, ((NI) 4));
					i_105060 = (NI)(TMP159);
				}
				goto LA4;
				LA15: ;
				{
					NI TMP160;
					NI TMP161;
					NI TMP162;
					NI TMP163;
					NI TMP164;
					nimln(80, "unicode.nim");
					if ((NU)(i_105060) > (NU)(s->Sup.len)) raiseIndexError();
					if (!((NI)((NU32)(((NI) (((NU8)(s->data[i_105060]))))) >> (NU32)(((NI) 2))) == ((NI) 62))) goto LA18;
					nimln(85, "unicode.nim");
					nimln(88, "unicode.nim");
					nimln(87, "unicode.nim");
					nimln(86, "unicode.nim");
					nimln(85, "unicode.nim");
					if ((NU)(i_105060) > (NU)(s->Sup.len)) raiseIndexError();
					nimln(86, "unicode.nim");
					TMP160 = addInt(i_105060, ((NI) 1));
					if ((NU)((NI)(TMP160)) > (NU)(s->Sup.len)) raiseIndexError();
					nimln(87, "unicode.nim");
					TMP161 = addInt(i_105060, ((NI) 2));
					if ((NU)((NI)(TMP161)) > (NU)(s->Sup.len)) raiseIndexError();
					nimln(88, "unicode.nim");
					TMP162 = addInt(i_105060, ((NI) 3));
					if ((NU)((NI)(TMP162)) > (NU)(s->Sup.len)) raiseIndexError();
					nimln(89, "unicode.nim");
					TMP163 = addInt(i_105060, ((NI) 4));
					if ((NU)((NI)(TMP163)) > (NU)(s->Sup.len)) raiseIndexError();
					result_105062 = (NI)((NI)((NI)((NI)((NI)((NU32)(((NI) ((NI)(((NI) (((NU8)(s->data[i_105060])))) & ((NI) 3))))) << (NU32)(((NI) 24))) | (NI)((NU32)(((NI) ((NI)(((NI) (((NU8)(s->data[(NI)(TMP160)])))) & ((NI) 63))))) << (NU32)(((NI) 18)))) | (NI)((NU32)(((NI) ((NI)(((NI) (((NU8)(s->data[(NI)(TMP161)])))) & ((NI) 63))))) << (NU32)(((NI) 12)))) | (NI)((NU32)(((NI) ((NI)(((NI) (((NU8)(s->data[(NI)(TMP162)])))) & ((NI) 63))))) << (NU32)(((NI) 6)))) | ((NI) ((NI)(((NI) (((NU8)(s->data[(NI)(TMP163)])))) & ((NI) 63)))));
					nimln(90, "unicode.nim");
					TMP164 = addInt(i_105060, ((NI) 5));
					i_105060 = (NI)(TMP164);
				}
				goto LA4;
				LA18: ;
				{
					NI TMP165;
					NI TMP166;
					NI TMP167;
					NI TMP168;
					NI TMP169;
					NI TMP170;
					nimln(91, "unicode.nim");
					if ((NU)(i_105060) > (NU)(s->Sup.len)) raiseIndexError();
					if (!((NI)((NU32)(((NI) (((NU8)(s->data[i_105060]))))) >> (NU32)(((NI) 1))) == ((NI) 126))) goto LA21;
					nimln(97, "unicode.nim");
					nimln(101, "unicode.nim");
					nimln(100, "unicode.nim");
					nimln(99, "unicode.nim");
					nimln(98, "unicode.nim");
					nimln(97, "unicode.nim");
					if ((NU)(i_105060) > (NU)(s->Sup.len)) raiseIndexError();
					nimln(98, "unicode.nim");
					TMP165 = addInt(i_105060, ((NI) 1));
					if ((NU)((NI)(TMP165)) > (NU)(s->Sup.len)) raiseIndexError();
					nimln(99, "unicode.nim");
					TMP166 = addInt(i_105060, ((NI) 2));
					if ((NU)((NI)(TMP166)) > (NU)(s->Sup.len)) raiseIndexError();
					nimln(100, "unicode.nim");
					TMP167 = addInt(i_105060, ((NI) 3));
					if ((NU)((NI)(TMP167)) > (NU)(s->Sup.len)) raiseIndexError();
					nimln(101, "unicode.nim");
					TMP168 = addInt(i_105060, ((NI) 4));
					if ((NU)((NI)(TMP168)) > (NU)(s->Sup.len)) raiseIndexError();
					nimln(102, "unicode.nim");
					TMP169 = addInt(i_105060, ((NI) 5));
					if ((NU)((NI)(TMP169)) > (NU)(s->Sup.len)) raiseIndexError();
					result_105062 = (NI)((NI)((NI)((NI)((NI)((NI)((NU32)(((NI) ((NI)(((NI) (((NU8)(s->data[i_105060])))) & ((NI) 1))))) << (NU32)(((NI) 30))) | (NI)((NU32)(((NI) ((NI)(((NI) (((NU8)(s->data[(NI)(TMP165)])))) & ((NI) 63))))) << (NU32)(((NI) 24)))) | (NI)((NU32)(((NI) ((NI)(((NI) (((NU8)(s->data[(NI)(TMP166)])))) & ((NI) 63))))) << (NU32)(((NI) 18)))) | (NI)((NU32)(((NI) ((NI)(((NI) (((NU8)(s->data[(NI)(TMP167)])))) & ((NI) 63))))) << (NU32)(((NI) 12)))) | (NI)((NU32)(((NI) ((NI)(((NI) (((NU8)(s->data[(NI)(TMP168)])))) & ((NI) 63))))) << (NU32)(((NI) 6)))) | ((NI) ((NI)(((NI) (((NU8)(s->data[(NI)(TMP169)])))) & ((NI) 63)))));
					nimln(103, "unicode.nim");
					TMP170 = addInt(i_105060, ((NI) 6));
					i_105060 = (NI)(TMP170);
				}
				goto LA4;
				LA21: ;
				{
					NI TMP171;
					nimln(105, "unicode.nim");
					if ((NU)(i_105060) > (NU)(s->Sup.len)) raiseIndexError();
					result_105062 = ((NI) (((NU8)(s->data[i_105060]))));
					nimln(106, "unicode.nim");
					TMP171 = addInt(i_105060, ((NI) 1));
					i_105060 = (NI)(TMP171);
				}
				LA4: ;
				nimln(1251, "unicode.nim");
				c_105036 = result_105062;
				nimln(36, "csfml_util.nim");
				result = (TY105018*) incrSeq(&(result)->Sup, sizeof(NU32));
				result->data[result->Sup.len-1] = ((NU32) (c_105036));
			} LA3: ;
		}
	}
	nimln(37, "csfml_util.nim");
	result = (TY105018*) incrSeq(&(result)->Sup, sizeof(NU32));
	result->data[result->Sup.len-1] = ((NU32) 0);
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, tobool_105085)(int x) {
	NIM_BOOL result;
	nimfr("toBool", "csfml_util.nim")
	result = 0;
	nimln(39, "csfml_util.nim");
	result = !((x == ((NI32) 0)));
	popFrame();
	return result;
}

N_NIMCALL(int, toboolint_105096)(NIM_BOOL x) {
	int result;
	NI LOC1;
	nimfr("toBoolInt", "csfml_util.nim")
	result = 0;
	nimln(41, "csfml_util.nim");
	LOC1 = 0;
	{
		if (!x) goto LA4;
		LOC1 = ((NI) 1);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) 0);
	}
	LA2: ;
	result = ((int) (LOC1));
	popFrame();
	return result;
}

N_NIMCALL(NU32, HEX7C_105107)(NU32 a, NU32 b) {
	NU32 result;
	nimfr("|", "csfml_util.nim")
	result = 0;
	nimln(44, "csfml_util.nim");
	result = (NU32)(a | b);
	popFrame();
	return result;
}

N_NIMCALL(NU32, toruneu32_105130)(NI x) {
	NU32 result;
	nimfr("toRuneU32", "csfml_util.nim")
	result = 0;
	nimln(47, "csfml_util.nim");
	result = ((NU32) (x));
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, torune_105140)(NU32 x) {
	NI result;
	nimfr("toRune", "csfml_util.nim")
	result = 0;
	nimln(49, "csfml_util.nim");
	result = ((NI)chckRange(x, ((NI) (-2147483647 -1)), ((NI) 2147483647)));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, csfml_csfml_utilInit)(void) {
	nimfr("csfml_util", "csfml_util.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, csfml_csfml_utilDatInit)(void) {
NTI105018.size = sizeof(TY105018*);
NTI105018.kind = 24;
NTI105018.base = (&NTI124);
NTI105018.flags = 2;
NTI105018.marker = TMP149;
}

