/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -Ic:\Nim\lib -o c:\users\202378\documents\github\spacebarrace\src\nimcache\csfml_csfml_audio.o c:\users\202378\documents\github\spacebarrace\src\nimcache\csfml_csfml_audio.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct TY13606 TY13606;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct SoundbufferHEX3Aobjecttype114447 SoundbufferHEX3Aobjecttype114447;
typedef struct SoundHEX3Aobjecttype114443 SoundHEX3Aobjecttype114443;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(SoundbufferHEX3Aobjecttype114447*, TY114636) (NCSTRING filename);
typedef N_CDECL_PTR(SoundHEX3Aobjecttype114443*, TY114553) (void);
typedef N_CDECL_PTR(void, TY114570) (SoundHEX3Aobjecttype114443* sound, SoundbufferHEX3Aobjecttype114447* buffer);
typedef N_CDECL_PTR(void, TY114561) (SoundHEX3Aobjecttype114443* sound);
struct  SoundbufferHEX3Aobjecttype114447  {
char dummy;
};
struct  SoundHEX3Aobjecttype114443  {
char dummy;
};
struct TY13606 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_NIMCALL(TY13606*, newseq_114799)(NI len);
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
STRING_LITERAL(TMP324, "csfml-audio-2.dll", 17);
STRING_LITERAL(TMP325, "csfml-audio-2.dll", 17);
static void* TMP323;
TY114636 Dl_114635;
TY114553 Dl_114552;
TY114570 Dl_114569;
extern TFrame* frameptr_17042;
TY114561 Dl_114560;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(SoundHEX3Aobjecttype114443*, newsound_114758)(SoundbufferHEX3Aobjecttype114447* buffer) {
	SoundHEX3Aobjecttype114443* result;
	nimfr("newSound", "csfml_audio.nim")
{	result = 0;
	nimln(34, "csfml_audio.nim");
	result = Dl_114552();
	nimln(35, "csfml_audio.nim");
	{
		if (!(result == NIM_NIL)) goto LA3;
		result = NIM_NIL;
		goto BeforeRet;
	}
	LA3: ;
	nimln(36, "csfml_audio.nim");
	Dl_114569(result, buffer);
	}BeforeRet: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, csfml_csfml_audioInit)(void) {
	nimfr("csfml_audio", "csfml_audio.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, csfml_csfml_audioDatInit)(void) {
if (!((TMP323 = nimLoadLibrary((NimStringDesc*) &TMP324))
)) nimLoadLibraryError((NimStringDesc*) &TMP325);
	Dl_114635 = (TY114636) nimGetProcAddr(TMP323, "sfSoundBuffer_createFromFile");
	Dl_114552 = (TY114553) nimGetProcAddr(TMP323, "sfSound_create");
	Dl_114569 = (TY114570) nimGetProcAddr(TMP323, "sfSound_setBuffer");
	Dl_114560 = (TY114561) nimGetProcAddr(TMP323, "sfSound_play");
}

