/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -Ic:\Nim\lib -o c:\users\202378\documents\github\spacebarrace\src\nimcache\csfml_csfml_window.o c:\users\202378\documents\github\spacebarrace\src\nimcache\csfml_csfml_window.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct TY108209 TY108209;
typedef struct Videomode107919 Videomode107919;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Contextsettings107943 Contextsettings107943;
struct  Videomode107919  {
int width;
int height;
int bitsperpixel;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Contextsettings107943  {
int depthbits;
int stencilbits;
int antialiasinglevel;
int majorversion;
int minorversion;
};
struct TY108209 {
  TGenericSeq Sup;
  Videomode107919 data[SEQ_DECL_SIZE];
};
N_NIMCALL(TY108209*, newseq_108204)(NI len);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
TNimType NTI107919; /* VideoMode */
extern TNimType NTI5811; /* cint */
extern TFrame* frameptr_17042;
TNimType NTI107667; /* KeyCode */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(Videomode107919, videomode_108140)(int modewidth, int modeheight, int bitsperpixel) {
	Videomode107919 result;
	nimfr("videoMode", "csfml_window.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(72, "csfml_window.nim");
	result.width = modewidth;
	nimln(73, "csfml_window.nim");
	result.height = modeheight;
	nimln(74, "csfml_window.nim");
	result.bitsperpixel = bitsperpixel;
	popFrame();
	return result;
}

N_NIMCALL(NU32, tobitmasku32_108281)(NI32 a) {
	NU32 result;
	nimfr("toBitMaskU32", "csfml_window.nim")
	result = 0;
	nimln(98, "csfml_window.nim");
	result = ((NU32) (a));
	popFrame();
	return result;
}

N_NIMCALL(Contextsettings107943, contextsettings_108099)(int depth, int stencil, int antialiasing, int major, int minor) {
	Contextsettings107943 result;
	nimfr("contextSettings", "csfml_window.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(46, "csfml_window.nim");
	result.depthbits = depth;
	nimln(47, "csfml_window.nim");
	result.stencilbits = stencil;
	nimln(48, "csfml_window.nim");
	result.antialiasinglevel = antialiasing;
	nimln(49, "csfml_window.nim");
	result.majorversion = major;
	nimln(50, "csfml_window.nim");
	result.minorversion = minor;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, csfml_csfml_windowInit)(void) {
	nimfr("csfml_window", "csfml_window.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, csfml_csfml_windowDatInit)(void) {
static TNimNode* TMP174[3];
static TNimNode* TMP366[103];
NI TMP368;
static char* NIM_CONST TMP367[103] = {
"Unknown", 
"A", 
"B", 
"C", 
"D", 
"E", 
"F", 
"G", 
"H", 
"I", 
"J", 
"K", 
"L", 
"M", 
"N", 
"O", 
"P", 
"Q", 
"R", 
"S", 
"T", 
"U", 
"V", 
"W", 
"X", 
"Y", 
"Z", 
"Num0", 
"Num1", 
"Num2", 
"Num3", 
"Num4", 
"Num5", 
"Num6", 
"Num7", 
"Num8", 
"Num9", 
"Escape", 
"LControl", 
"LShift", 
"LAlt", 
"LSystem", 
"RControl", 
"RShift", 
"RAlt", 
"RSystem", 
"Menu", 
"LBracket", 
"RBracket", 
"SemiColon", 
"Comma", 
"Period", 
"Quote", 
"Slash", 
"BackSlash", 
"Tilde", 
"Equal", 
"Dash", 
"Space", 
"Return", 
"Back", 
"Tab", 
"PageUp", 
"PageDown", 
"End", 
"Home", 
"Insert", 
"Delete", 
"Add", 
"Subtract", 
"Multiply", 
"Divide", 
"Left", 
"Right", 
"Up", 
"Down", 
"Numpad0", 
"Numpad1", 
"Numpad2", 
"Numpad3", 
"Numpad4", 
"Numpad5", 
"Numpad6", 
"Numpad7", 
"Numpad8", 
"Numpad9", 
"F1", 
"F2", 
"F3", 
"F4", 
"F5", 
"F6", 
"F7", 
"F8", 
"F9", 
"F10", 
"F11", 
"F12", 
"F13", 
"F14", 
"F15", 
"Pause", 
"Count"};
static TNimNode TMP172[108];
NTI107919.size = sizeof(Videomode107919);
NTI107919.kind = 18;
NTI107919.base = 0;
NTI107919.flags = 3;
TMP174[0] = &TMP172[1];
TMP172[1].kind = 1;
TMP172[1].offset = offsetof(Videomode107919, width);
TMP172[1].typ = (&NTI5811);
TMP172[1].name = "width";
TMP174[1] = &TMP172[2];
TMP172[2].kind = 1;
TMP172[2].offset = offsetof(Videomode107919, height);
TMP172[2].typ = (&NTI5811);
TMP172[2].name = "height";
TMP174[2] = &TMP172[3];
TMP172[3].kind = 1;
TMP172[3].offset = offsetof(Videomode107919, bitsperpixel);
TMP172[3].typ = (&NTI5811);
TMP172[3].name = "bitsPerPixel";
TMP172[0].len = 3; TMP172[0].kind = 2; TMP172[0].sons = &TMP174[0];
NTI107919.node = &TMP172[0];
NTI107667.size = sizeof(NI32);
NTI107667.kind = 14;
NTI107667.base = 0;
NTI107667.flags = 3;
for (TMP368 = 0; TMP368 < 103; TMP368++) {
TMP172[TMP368+4].kind = 1;
TMP172[TMP368+4].offset = TMP368;
TMP172[TMP368+4].name = TMP367[TMP368];
TMP366[TMP368] = &TMP172[TMP368+4];
}
TMP172[4].offset = -1;
TMP172[5].offset = 0;
TMP172[6].offset = 1;
TMP172[7].offset = 2;
TMP172[8].offset = 3;
TMP172[9].offset = 4;
TMP172[10].offset = 5;
TMP172[11].offset = 6;
TMP172[12].offset = 7;
TMP172[13].offset = 8;
TMP172[14].offset = 9;
TMP172[15].offset = 10;
TMP172[16].offset = 11;
TMP172[17].offset = 12;
TMP172[18].offset = 13;
TMP172[19].offset = 14;
TMP172[20].offset = 15;
TMP172[21].offset = 16;
TMP172[22].offset = 17;
TMP172[23].offset = 18;
TMP172[24].offset = 19;
TMP172[25].offset = 20;
TMP172[26].offset = 21;
TMP172[27].offset = 22;
TMP172[28].offset = 23;
TMP172[29].offset = 24;
TMP172[30].offset = 25;
TMP172[31].offset = 26;
TMP172[32].offset = 27;
TMP172[33].offset = 28;
TMP172[34].offset = 29;
TMP172[35].offset = 30;
TMP172[36].offset = 31;
TMP172[37].offset = 32;
TMP172[38].offset = 33;
TMP172[39].offset = 34;
TMP172[40].offset = 35;
TMP172[41].offset = 36;
TMP172[42].offset = 37;
TMP172[43].offset = 38;
TMP172[44].offset = 39;
TMP172[45].offset = 40;
TMP172[46].offset = 41;
TMP172[47].offset = 42;
TMP172[48].offset = 43;
TMP172[49].offset = 44;
TMP172[50].offset = 45;
TMP172[51].offset = 46;
TMP172[52].offset = 47;
TMP172[53].offset = 48;
TMP172[54].offset = 49;
TMP172[55].offset = 50;
TMP172[56].offset = 51;
TMP172[57].offset = 52;
TMP172[58].offset = 53;
TMP172[59].offset = 54;
TMP172[60].offset = 55;
TMP172[61].offset = 56;
TMP172[62].offset = 57;
TMP172[63].offset = 58;
TMP172[64].offset = 59;
TMP172[65].offset = 60;
TMP172[66].offset = 61;
TMP172[67].offset = 62;
TMP172[68].offset = 63;
TMP172[69].offset = 64;
TMP172[70].offset = 65;
TMP172[71].offset = 66;
TMP172[72].offset = 67;
TMP172[73].offset = 68;
TMP172[74].offset = 69;
TMP172[75].offset = 70;
TMP172[76].offset = 71;
TMP172[77].offset = 72;
TMP172[78].offset = 73;
TMP172[79].offset = 74;
TMP172[80].offset = 75;
TMP172[81].offset = 76;
TMP172[82].offset = 77;
TMP172[83].offset = 78;
TMP172[84].offset = 79;
TMP172[85].offset = 80;
TMP172[86].offset = 81;
TMP172[87].offset = 82;
TMP172[88].offset = 83;
TMP172[89].offset = 84;
TMP172[90].offset = 85;
TMP172[91].offset = 86;
TMP172[92].offset = 87;
TMP172[93].offset = 88;
TMP172[94].offset = 89;
TMP172[95].offset = 90;
TMP172[96].offset = 91;
TMP172[97].offset = 92;
TMP172[98].offset = 93;
TMP172[99].offset = 94;
TMP172[100].offset = 95;
TMP172[101].offset = 96;
TMP172[102].offset = 97;
TMP172[103].offset = 98;
TMP172[104].offset = 99;
TMP172[105].offset = 100;
TMP172[106].offset = 101;
TMP172[107].len = 103; TMP172[107].kind = 2; TMP172[107].sons = &TMP366[0];
NTI107667.node = &TMP172[107];
NTI107667.flags = 1<<2;
}

