/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -Ic:\Nim\lib -o c:\users\202378\documents\github\spacebarrace\src\nimcache\stdlib_winlean.o c:\users\202378\documents\github\spacebarrace\src\nimcache\stdlib_winlean.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct Tguid129814 Tguid129814;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct Tfiletime127445 Tfiletime127445;
typedef NI8 TY129827[8];
struct  Tguid129814  {
NI32 D1;
NI16 D2;
NI16 D3;
TY129827 D4;
};
typedef NI8 TY129908[8];
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_STDCALL_PTR(void, TY128825) (Tfiletime127445* lpsystemtimeasfiletime);
struct  Tfiletime127445  {
NI32 dwlowdatetime;
NI32 dwhighdatetime;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
NIM_CONST TY129908 TMP194 = {((NI8) -114),
((NI8) -23),
((NI8) 118),
((NI8) -27),
((NI8) -116),
((NI8) 116),
((NI8) 6),
((NI8) 62)}
;
NIM_CONST TY129908 TMP195 = {((NI8) -107),
((NI8) -54),
((NI8) 0),
((NI8) -128),
((NI8) 95),
((NI8) 72),
((NI8) -95),
((NI8) -110)}
;
STRING_LITERAL(TMP206, "kernel32", 8);
STRING_LITERAL(TMP207, "kernel32", 8);
Tguid129814 Wsaidconnectex_129910;
Tguid129814 Wsaidacceptex_129914;
Tguid129814 Wsaidgetacceptexsockaddrs_129918;
static void* TMP205;
TY128825 Dl_128824;

N_NIMCALL(NI64, rdfiletime_128804)(Tfiletime127445 f) {
	NI64 result;
	result = 0;
	result = (NI64)(((NI64)(NU64)(NU32)(f.dwlowdatetime)) | (NI64)((NU64)(((NI64)(NU64)(NU32)(f.dwhighdatetime))) << (NU64)(IL64(32))));
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanInit)(void) {
	Tguid129814 LOC1;
	Tguid129814 LOC2;
	Tguid129814 LOC3;
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.D1 = ((NI32) 631375801);
	LOC1.D2 = ((NI16) -8717);
	LOC1.D3 = ((NI16) 18016);
	memcpy((void*)LOC1.D4, (NIM_CONST void*)TMP194, sizeof(LOC1.D4));
	Wsaidconnectex_129910 = LOC1;
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	LOC2.D1 = ((NI32) -1254720015);
	LOC2.D2 = ((NI16) -13396);
	LOC2.D3 = ((NI16) 4559);
	memcpy((void*)LOC2.D4, (NIM_CONST void*)TMP195, sizeof(LOC2.D4));
	Wsaidacceptex_129914 = LOC2;
	memset((void*)(&LOC3), 0, sizeof(LOC3));
	LOC3.D1 = ((NI32) -1254720014);
	LOC3.D2 = ((NI16) -13396);
	LOC3.D3 = ((NI16) 4559);
	memcpy((void*)LOC3.D4, (NIM_CONST void*)TMP195, sizeof(LOC3.D4));
	Wsaidgetacceptexsockaddrs_129918 = LOC3;
}

NIM_EXTERNC N_NOINLINE(void, stdlib_winleanDatInit)(void) {
if (!((TMP205 = nimLoadLibrary((NimStringDesc*) &TMP206))
)) nimLoadLibraryError((NimStringDesc*) &TMP207);
	Dl_128824 = (TY128825) nimGetProcAddr(TMP205, "GetSystemTimeAsFileTime");
}

