/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -Ic:\Nim\lib -o c:\users\202378\documents\github\spacebarrace\src\nimcache\stdlib_strutils.o c:\users\202378\documents\github\spacebarrace\src\nimcache\stdlib_strutils.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Valueerror3449 Valueerror3449;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Tcell46746 Tcell46746;
typedef struct Tcellseq46762 Tcellseq46762;
typedef struct Tgcheap48616 Tgcheap48616;
typedef struct Tcellset46758 Tcellset46758;
typedef struct Tpagedesc46754 Tpagedesc46754;
typedef struct Tmemregion28610 Tmemregion28610;
typedef struct Tsmallchunk27840 Tsmallchunk27840;
typedef struct Tllchunk28604 Tllchunk28604;
typedef struct Tbigchunk27842 Tbigchunk27842;
typedef struct Tintset27817 Tintset27817;
typedef struct Ttrunk27813 Ttrunk27813;
typedef struct Tavlnode28608 Tavlnode28608;
typedef struct Tgcstat48614 Tgcstat48614;
typedef struct Tbasechunk27838 Tbasechunk27838;
typedef struct Tfreecell27830 Tfreecell27830;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Valueerror3449  {
  Exception Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Tcell46746  {
NI refcount;
TNimType* typ;
};
struct  Tcellseq46762  {
NI len;
NI cap;
Tcell46746** d;
};
struct  Tcellset46758  {
NI counter;
NI max;
Tpagedesc46754* head;
Tpagedesc46754** data;
};
typedef Tsmallchunk27840* TY28622[512];
typedef Ttrunk27813* Ttrunkbuckets27815[256];
struct  Tintset27817  {
Ttrunkbuckets27815 data;
};
struct  Tmemregion28610  {
NI minlargeobj;
NI maxlargeobj;
TY28622 freesmallchunks;
Tllchunk28604* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Tbigchunk27842* freechunkslist;
Tintset27817 chunkstarts;
Tavlnode28608* root;
Tavlnode28608* deleted;
Tavlnode28608* last;
Tavlnode28608* freeavlnodes;
};
struct  Tgcstat48614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Tgcheap48616  {
void* stackbottom;
NI cyclethreshold;
Tcellseq46762 zct;
Tcellseq46762 decstack;
Tcellset46758 cycleroots;
Tcellseq46762 tempstack;
NI recgclock;
Tmemregion28610 region;
Tgcstat48614 stat;
};
typedef NI TY27820[16];
struct  Tpagedesc46754  {
Tpagedesc46754* next;
NI key;
TY27820 bits;
};
struct  Tbasechunk27838  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Tsmallchunk27840  {
  Tbasechunk27838 Sup;
Tsmallchunk27840* next;
Tsmallchunk27840* prev;
Tfreecell27830* freelist;
NI free;
NI acc;
NF data;
};
struct  Tllchunk28604  {
NI size;
NI acc;
Tllchunk28604* next;
};
struct  Tbigchunk27842  {
  Tbasechunk27838 Sup;
Tbigchunk27842* next;
Tbigchunk27842* prev;
NI align;
NF data;
};
struct  Ttrunk27813  {
Ttrunk27813* next;
NI key;
TY27820 bits;
};
typedef Tavlnode28608* TY28614[2];
struct  Tavlnode28608  {
TY28614 link;
NI key;
NI upperbound;
NI level;
};
struct  Tfreecell27830  {
Tfreecell27830* next;
NI zerofield;
};
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NI, npuParseInt)(NimStringDesc* s, NI* number, NI start);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr);
static N_INLINE(void, rtladdzct_51804)(Tcell46746* c);
N_NOINLINE(void, addzct_50217)(Tcellseq46762* s, Tcell46746* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c);
N_NIMCALL(NIM_CHAR, nsuToUpperChar)(NIM_CHAR c);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_NIMCALL(void, nsuAddf)(NimStringDesc** s, NimStringDesc* formatstr, NimStringDesc** a, NI aLen0);
N_NOINLINE(void, invalidformatstring_123759)(void);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NIMCALL(NI, findnormalized_123730)(NimStringDesc* x, NimStringDesc** inarray, NI inarrayLen0);
N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_76643, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
STRING_LITERAL(TMP273, "invalid integer: ", 17);
STRING_LITERAL(TMP335, "invalid format string", 21);
extern TFrame* frameptr_17042;
extern TNimType NTI22801; /* ref ValueError */
extern TNimType NTI3449; /* ValueError */
extern Tgcheap48616 gch_48644;

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars) {
	NimStringDesc* result;
	nimfr("intToStr", "strutils.nim")
	result = 0;
	nimln(412, "strutils.nim");
	if (x == (-2147483647 -1)) raiseOverflow();
	result = nimIntToStr((x > 0? (x) : -(x)));
	{
		NI i_120462;
		NI HEX3Atmp_120464;
		NI TMP208;
		NI res_120467;
		i_120462 = 0;
		HEX3Atmp_120464 = 0;
		nimln(413, "strutils.nim");
		TMP208 = subInt(((NI) (minchars)), (result ? result->Sup.len : 0));
		HEX3Atmp_120464 = (NI)(TMP208);
		nimln(1598, "system.nim");
		res_120467 = ((NI) 1);
		{
			nimln(1599, "system.nim");
			while (1) {
				NimStringDesc* LOC4;
				NI TMP209;
				if (!(res_120467 <= HEX3Atmp_120464)) goto LA3;
				nimln(1600, "system.nim");
				i_120462 = res_120467;
				nimln(414, "strutils.nim");
				LOC4 = 0;
				LOC4 = rawNewString(result->Sup.len + 1);
appendChar(LOC4, 48);
appendString(LOC4, result);
				result = LOC4;
				nimln(1619, "system.nim");
				TMP209 = addInt(res_120467, ((NI) 1));
				res_120467 = (NI)(TMP209);
			} LA3: ;
		}
	}
	nimln(415, "strutils.nim");
	{
		NimStringDesc* LOC9;
		if (!(x < ((NI) 0))) goto LA7;
		nimln(416, "strutils.nim");
		LOC9 = 0;
		LOC9 = rawNewString(result->Sup.len + 1);
appendChar(LOC9, 45);
appendString(LOC9, result);
		result = LOC9;
	}
	LA7: ;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NIM_CHAR c, NI count) {
	NimStringDesc* result;
	nimfr("repeat", "strutils.nim")
	result = 0;
	nimln(514, "strutils.nim");
	result = mnewString(count);
	{
		NI i_120773;
		NI HEX3Atmp_120775;
		NI TMP259;
		NI res_120778;
		i_120773 = 0;
		HEX3Atmp_120775 = 0;
		nimln(515, "strutils.nim");
		TMP259 = subInt(((NI) (count)), ((NI) 1));
		HEX3Atmp_120775 = (NI)(TMP259);
		nimln(1598, "system.nim");
		res_120778 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP260;
				if (!(res_120778 <= ((NI) (HEX3Atmp_120775)))) goto LA3;
				nimln(1600, "system.nim");
				i_120773 = ((NI)chckRange(res_120778, ((NI) -1), ((NI) 2147483646)));
				nimln(515, "strutils.nim");
				if ((NU)(i_120773) > (NU)(result->Sup.len)) raiseIndexError();
				result->data[i_120773] = c;
				nimln(1619, "system.nim");
				TMP260 = addInt(res_120778, ((NI) 1));
				res_120778 = (NI)(TMP260);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr) {
	Tcell46746* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	result = ((Tcell46746*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(Tcell46746))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_51804)(Tcell46746* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_50217((&gch_48644.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		Tcell46746* c;
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_50246(src);
		nimln(169, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		Tcell46746* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_50246((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(168, "gc.nim");
			if (!((NU32)((*c).refcount) < (NU32)(((NI) 8)))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_51804(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s) {
	NI result;
	NI L;
	nimfr("parseInt", "strutils.nim")
	result = 0;
	nimln(423, "strutils.nim");
	L = npuParseInt(s, (&result), ((NI) 0));
	nimln(424, "strutils.nim");
	{
		NIM_BOOL LOC3;
		Valueerror3449* e_120494;
		NimStringDesc* LOC7;
		LOC3 = 0;
		LOC3 = !((L == (s ? s->Sup.len : 0)));
		if (LOC3) goto LA4;
		LOC3 = (L == ((NI) 0));
		LA4: ;
		if (!LOC3) goto LA5;
		e_120494 = 0;
		nimln(2265, "system.nim");
		e_120494 = (Valueerror3449*) newObj((&NTI22801), sizeof(Valueerror3449));
		(*e_120494).Sup.Sup.m_type = (&NTI3449);
		nimln(2266, "system.nim");
		nimln(425, "strutils.nim");
		LOC7 = 0;
		LOC7 = rawNewString(s->Sup.len + 17);
appendString(LOC7, ((NimStringDesc*) &TMP273));
appendString(LOC7, s);
		asgnRefNoCycle((void**) (&(*e_120494).Sup.message), LOC7);
		raiseException((Exception*)e_120494, "ValueError");
	}
	LA5: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c) {
	NIM_CHAR result;
	nimfr("toLower", "strutils.nim")
	result = 0;
	nimln(69, "strutils.nim");
	{
		NI TMP275;
		if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA3;
		nimln(70, "strutils.nim");
		TMP275 = addInt(((NI) (((NU8)(c)))), ((NI) 32));
		result = ((NIM_CHAR) (((NI)chckRange((NI)(TMP275), ((NI) 0), ((NI) 255)))));
	}
	goto LA1;
	LA3: ;
	{
		nimln(72, "strutils.nim");
		result = c;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nsuToLowerStr)(NimStringDesc* s) {
	NimStringDesc* result;
	nimfr("toLower", "strutils.nim")
	result = 0;
	nimln(81, "strutils.nim");
	result = mnewString(((NI)chckRange((s ? s->Sup.len : 0), ((NI) 0), ((NI) 2147483647))));
	{
		NI i_119091;
		NI HEX3Atmp_119093;
		NI TMP274;
		NI res_119096;
		i_119091 = 0;
		HEX3Atmp_119093 = 0;
		nimln(82, "strutils.nim");
		TMP274 = subInt((s ? s->Sup.len : 0), ((NI) 1));
		HEX3Atmp_119093 = (NI)(TMP274);
		nimln(1598, "system.nim");
		res_119096 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP276;
				if (!(res_119096 <= HEX3Atmp_119093)) goto LA3;
				nimln(1600, "system.nim");
				i_119091 = res_119096;
				nimln(83, "strutils.nim");
				if ((NU)(i_119091) > (NU)(result->Sup.len)) raiseIndexError();
				if ((NU)(i_119091) > (NU)(s->Sup.len)) raiseIndexError();
				result->data[i_119091] = nsuToLowerChar(s->data[i_119091]);
				nimln(1619, "system.nim");
				TMP276 = addInt(res_119096, ((NI) 1));
				res_119096 = (NI)(TMP276);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a, NimStringDesc* b) {
	NI result;
	NI i;
	NI m;
	NI TMP287;
	nimfr("cmpIgnoreCase", "strutils.nim")
{	result = 0;
	nimln(139, "strutils.nim");
	i = ((NI) 0);
	nimln(140, "strutils.nim");
	m = (((a ? a->Sup.len : 0) <= (b ? b->Sup.len : 0)) ? (a ? a->Sup.len : 0) : (b ? b->Sup.len : 0));
	{
		nimln(141, "strutils.nim");
		while (1) {
			NIM_CHAR LOC3;
			NIM_CHAR LOC4;
			NI TMP285;
			NI TMP286;
			if (!(i < m)) goto LA2;
			nimln(142, "strutils.nim");
			if ((NU)(i) > (NU)(a->Sup.len)) raiseIndexError();
			LOC3 = 0;
			LOC3 = nsuToLowerChar(a->data[i]);
			if ((NU)(i) > (NU)(b->Sup.len)) raiseIndexError();
			LOC4 = 0;
			LOC4 = nsuToLowerChar(b->data[i]);
			TMP285 = subInt(((NI) (((NU8)(LOC3)))), ((NI) (((NU8)(LOC4)))));
			result = (NI)(TMP285);
			nimln(143, "strutils.nim");
			{
				if (!!((result == ((NI) 0)))) goto LA7;
				goto BeforeRet;
			}
			LA7: ;
			nimln(144, "strutils.nim");
			TMP286 = addInt(i, ((NI) 1));
			i = (NI)(TMP286);
		} LA2: ;
	}
	nimln(145, "strutils.nim");
	TMP287 = subInt((a ? a->Sup.len : 0), (b ? b->Sup.len : 0));
	result = (NI)(TMP287);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_CHAR, nsuToUpperChar)(NIM_CHAR c) {
	NIM_CHAR result;
	nimfr("toUpper", "strutils.nim")
	result = 0;
	nimln(92, "strutils.nim");
	{
		NI TMP321;
		if (!(((NU8)(c)) >= ((NU8)(97)) && ((NU8)(c)) <= ((NU8)(122)))) goto LA3;
		nimln(93, "strutils.nim");
		TMP321 = subInt(((NI) (((NU8)(c)))), ((NI) 32));
		result = ((NIM_CHAR) (((NI)chckRange((NI)(TMP321), ((NI) 0), ((NI) 255)))));
	}
	goto LA1;
	LA3: ;
	{
		nimln(95, "strutils.nim");
		result = c;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nsuToUpperStr)(NimStringDesc* s) {
	NimStringDesc* result;
	nimfr("toUpper", "strutils.nim")
	result = 0;
	nimln(104, "strutils.nim");
	result = mnewString(((NI)chckRange((s ? s->Sup.len : 0), ((NI) 0), ((NI) 2147483647))));
	{
		NI i_119177;
		NI HEX3Atmp_119179;
		NI TMP320;
		NI res_119182;
		i_119177 = 0;
		HEX3Atmp_119179 = 0;
		nimln(105, "strutils.nim");
		TMP320 = subInt((s ? s->Sup.len : 0), ((NI) 1));
		HEX3Atmp_119179 = (NI)(TMP320);
		nimln(1598, "system.nim");
		res_119182 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP322;
				if (!(res_119182 <= HEX3Atmp_119179)) goto LA3;
				nimln(1600, "system.nim");
				i_119177 = res_119182;
				nimln(106, "strutils.nim");
				if ((NU)(i_119177) > (NU)(result->Sup.len)) raiseIndexError();
				if ((NU)(i_119177) > (NU)(s->Sup.len)) raiseIndexError();
				result->data[i_119177] = nsuToUpperChar(s->data[i_119177]);
				nimln(1619, "system.nim");
				TMP322 = addInt(res_119182, ((NI) 1));
				res_119182 = (NI)(TMP322);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Tcell46746* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_50246(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(168, "gc.nim");
		if (!((NU32)((*c).refcount) < (NU32)(((NI) 8)))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_51804(c);
	}
	LA3: ;
	popFrame();
}

N_NOINLINE(void, invalidformatstring_123759)(void) {
	Valueerror3449* e_123763;
	NimStringDesc* LOC1;
	nimfr("invalidFormatString", "strutils.nim")
	e_123763 = 0;
	nimln(2265, "system.nim");
	e_123763 = (Valueerror3449*) newObj((&NTI22801), sizeof(Valueerror3449));
	(*e_123763).Sup.Sup.m_type = (&NTI3449);
	nimln(2266, "system.nim");
	LOC1 = 0;
	LOC1 = (*e_123763).Sup.message; (*e_123763).Sup.message = copyStringRC1(((NimStringDesc*) &TMP335));
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(1289, "strutils.nim");
	raiseException((Exception*)e_123763, "ValueError");
	popFrame();
}

N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b) {
	NI result;
	NI i;
	NI j;
	nimfr("cmpIgnoreStyle", "strutils.nim")
	result = 0;
	i = ((NI) 0);
	j = ((NI) 0);
	{
		while (1) {
			NIM_CHAR aa;
			NIM_CHAR bb;
			{
				while (1) {
					if (!((NU8)(a->data[i]) == (NU8)(95))) goto LA4;
					i += ((NI) 1);
				} LA4: ;
			}
			{
				while (1) {
					if (!((NU8)(b->data[j]) == (NU8)(95))) goto LA6;
					j += ((NI) 1);
				} LA6: ;
			}
			aa = nsuToLowerChar(a->data[i]);
			bb = nsuToLowerChar(b->data[j]);
			result = (NI)(((NI) (((NU8)(aa)))) - ((NI) (((NU8)(bb)))));
			{
				NIM_BOOL LOC9;
				LOC9 = 0;
				LOC9 = !((result == ((NI) 0)));
				if (LOC9) goto LA10;
				LOC9 = ((NU8)(aa) == (NU8)(0));
				LA10: ;
				if (!LOC9) goto LA11;
				goto LA1;
			}
			LA11: ;
			i += ((NI) 1);
			j += ((NI) 1);
		}
	} LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, findnormalized_123730)(NimStringDesc* x, NimStringDesc** inarray, NI inarrayLen0) {
	NI result;
	NI i;
	nimfr("findNormalized", "strutils.nim")
{	result = 0;
	nimln(1281, "strutils.nim");
	i = ((NI) 0);
	{
		nimln(1282, "strutils.nim");
		while (1) {
			NI TMP349;
			if (!(i < (inarrayLen0-1))) goto LA2;
			nimln(1283, "strutils.nim");
			{
				NI LOC5;
				if ((NU)(i) >= (NU)(inarrayLen0)) raiseIndexError();
				LOC5 = 0;
				LOC5 = nsuCmpIgnoreStyle(x, inarray[i]);
				if (!(LOC5 == ((NI) 0))) goto LA6;
				result = i;
				goto BeforeRet;
			}
			LA6: ;
			nimln(1284, "strutils.nim");
			TMP349 = addInt(i, ((NI) 2));
			i = (NI)(TMP349);
		} LA2: ;
	}
	nimln(1286, "strutils.nim");
	result = ((NI) -1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, nsuAddf)(NimStringDesc** s, NimStringDesc* formatstr, NimStringDesc** a, NI aLen0) {
	NI i;
	NI num;
	nimfr("addf", "strutils.nim")
	nimln(1295, "strutils.nim");
	i = ((NI) 0);
	nimln(1296, "strutils.nim");
	num = ((NI) 0);
	{
		nimln(1297, "strutils.nim");
		while (1) {
			if (!(i < (formatstr ? formatstr->Sup.len : 0))) goto LA2;
			nimln(1298, "strutils.nim");
			{
				NI TMP334;
				if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
				if (!((NU8)(formatstr->data[i]) == (NU8)(36))) goto LA5;
				nimln(1299, "strutils.nim");
				TMP334 = addInt(i, ((NI) 1));
				if ((NU)((NI)(TMP334)) > (NU)(formatstr->Sup.len)) raiseIndexError();
				switch (((NU8)(formatstr->data[(NI)(TMP334)]))) {
				case 35:
				{
					NI TMP336;
					NI TMP337;
					nimln(1302, "strutils.nim");
					{
						if (!((NU32)((aLen0-1)) < (NU32)(num))) goto LA10;
						invalidformatstring_123759();
					}
					LA10: ;
					nimln(1303, "strutils.nim");
					if ((NU)(num) >= (NU)(aLen0)) raiseIndexError();
					(*s) = resizeString((*s), a[num]->Sup.len + 0);
appendString((*s), a[num]);
					nimln(1304, "strutils.nim");
					TMP336 = addInt(i, ((NI) 2));
					i = (NI)(TMP336);
					nimln(1305, "strutils.nim");
					TMP337 = addInt(num, ((NI) 1));
					num = (NI)(TMP337);
				}
				break;
				case 36:
				{
					NI TMP338;
					nimln(1307, "strutils.nim");
					(*s) = addChar((*s), 36);
					nimln(1308, "strutils.nim");
					TMP338 = addInt(i, ((NI) 2));
					i = (NI)(TMP338);
				}
				break;
				case 49 ... 57:
				case 45:
				{
					NI j;
					NI TMP339;
					NIM_BOOL negative;
					NI idx;
					nimln(1310, "strutils.nim");
					j = ((NI) 0);
					nimln(1311, "strutils.nim");
					TMP339 = addInt(i, ((NI) 1));
					i = (NI)(TMP339);
					nimln(1312, "strutils.nim");
					if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
					negative = ((NU8)(formatstr->data[i]) == (NU8)(45));
					nimln(1313, "strutils.nim");
					{
						NI TMP340;
						if (!negative) goto LA16;
						TMP340 = addInt(i, ((NI) 1));
						i = (NI)(TMP340);
					}
					LA16: ;
					{
						nimln(1314, "strutils.nim");
						while (1) {
							NI TMP341;
							NI TMP342;
							NI TMP343;
							NI TMP344;
							if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
							if (!(((NU8)(formatstr->data[i])) >= ((NU8)(48)) && ((NU8)(formatstr->data[i])) <= ((NU8)(57)))) goto LA19;
							nimln(1315, "strutils.nim");
							TMP341 = mulInt(j, ((NI) 10));
							if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
							TMP342 = addInt((NI)(TMP341), ((NI) (((NU8)(formatstr->data[i])))));
							TMP343 = subInt((NI)(TMP342), ((NI) 48));
							j = (NI)(TMP343);
							nimln(1316, "strutils.nim");
							TMP344 = addInt(i, ((NI) 1));
							i = (NI)(TMP344);
						} LA19: ;
					}
					nimln(1317, "strutils.nim");
					{
						NI TMP345;
						if (!!(negative)) goto LA22;
						TMP345 = subInt(j, ((NI) 1));
						idx = (NI)(TMP345);
					}
					goto LA20;
					LA22: ;
					{
						NI TMP346;
						TMP346 = subInt(aLen0, j);
						idx = (NI)(TMP346);
					}
					LA20: ;
					nimln(1318, "strutils.nim");
					{
						if (!((NU32)((aLen0-1)) < (NU32)(idx))) goto LA27;
						invalidformatstring_123759();
					}
					LA27: ;
					nimln(1319, "strutils.nim");
					if ((NU)(idx) >= (NU)(aLen0)) raiseIndexError();
					(*s) = resizeString((*s), a[idx]->Sup.len + 0);
appendString((*s), a[idx]);
				}
				break;
				case 123:
				{
					NI j;
					NI TMP347;
					NI x;
					NI TMP350;
					NI TMP351;
					NimStringDesc* LOC32;
					NI TMP353;
					nimln(1321, "strutils.nim");
					TMP347 = addInt(i, ((NI) 1));
					j = (NI)(TMP347);
					{
						nimln(1322, "strutils.nim");
						while (1) {
							NI TMP348;
							if ((NU)(j) > (NU)(formatstr->Sup.len)) raiseIndexError();
							if (!!((((NU8)(formatstr->data[j])) == ((NU8)(0)) || ((NU8)(formatstr->data[j])) == ((NU8)(125))))) goto LA31;
							TMP348 = addInt(j, ((NI) 1));
							j = (NI)(TMP348);
						} LA31: ;
					}
					nimln(1323, "strutils.nim");
					TMP350 = addInt(i, ((NI) 2));
					TMP351 = subInt(j, ((NI) 1));
					LOC32 = 0;
					LOC32 = copyStrLast(formatstr, (NI)(TMP350), (NI)(TMP351));
					x = findnormalized_123730(LOC32, a, aLen0);
					nimln(1324, "strutils.nim");
					{
						NIM_BOOL LOC35;
						NI TMP352;
						LOC35 = 0;
						LOC35 = (((NI) 0) <= x);
						if (!(LOC35)) goto LA36;
						LOC35 = (x < (aLen0-1));
						LA36: ;
						if (!LOC35) goto LA37;
						TMP352 = addInt(x, ((NI) 1));
						if ((NU)((NI)(TMP352)) >= (NU)(aLen0)) raiseIndexError();
						(*s) = resizeString((*s), a[(NI)(TMP352)]->Sup.len + 0);
appendString((*s), a[(NI)(TMP352)]);
					}
					goto LA33;
					LA37: ;
					{
						nimln(1325, "strutils.nim");
						invalidformatstring_123759();
					}
					LA33: ;
					nimln(1326, "strutils.nim");
					TMP353 = addInt(j, ((NI) 1));
					i = (NI)(TMP353);
				}
				break;
				case 97 ... 122:
				case 65 ... 90:
				case 128 ... 255:
				case 95:
				{
					NI j;
					NI TMP354;
					NI x;
					NI TMP356;
					NI TMP357;
					NimStringDesc* LOC43;
					nimln(1328, "strutils.nim");
					TMP354 = addInt(i, ((NI) 1));
					j = (NI)(TMP354);
					{
						nimln(1329, "strutils.nim");
						while (1) {
							NI TMP355;
							if ((NU)(j) > (NU)(formatstr->Sup.len)) raiseIndexError();
							if (!(((NU8)(formatstr->data[j])) >= ((NU8)(97)) && ((NU8)(formatstr->data[j])) <= ((NU8)(122)) || ((NU8)(formatstr->data[j])) >= ((NU8)(65)) && ((NU8)(formatstr->data[j])) <= ((NU8)(90)) || ((NU8)(formatstr->data[j])) >= ((NU8)(48)) && ((NU8)(formatstr->data[j])) <= ((NU8)(57)) || ((NU8)(formatstr->data[j])) >= ((NU8)(128)) && ((NU8)(formatstr->data[j])) <= ((NU8)(255)) || ((NU8)(formatstr->data[j])) == ((NU8)(95)))) goto LA42;
							TMP355 = addInt(j, ((NI) 1));
							j = (NI)(TMP355);
						} LA42: ;
					}
					nimln(1330, "strutils.nim");
					TMP356 = addInt(i, ((NI) 1));
					TMP357 = subInt(j, ((NI) 1));
					LOC43 = 0;
					LOC43 = copyStrLast(formatstr, (NI)(TMP356), (NI)(TMP357));
					x = findnormalized_123730(LOC43, a, aLen0);
					nimln(1331, "strutils.nim");
					{
						NIM_BOOL LOC46;
						NI TMP358;
						LOC46 = 0;
						LOC46 = (((NI) 0) <= x);
						if (!(LOC46)) goto LA47;
						LOC46 = (x < (aLen0-1));
						LA47: ;
						if (!LOC46) goto LA48;
						TMP358 = addInt(x, ((NI) 1));
						if ((NU)((NI)(TMP358)) >= (NU)(aLen0)) raiseIndexError();
						(*s) = resizeString((*s), a[(NI)(TMP358)]->Sup.len + 0);
appendString((*s), a[(NI)(TMP358)]);
					}
					goto LA44;
					LA48: ;
					{
						nimln(1332, "strutils.nim");
						invalidformatstring_123759();
					}
					LA44: ;
					nimln(1333, "strutils.nim");
					i = j;
				}
				break;
				default:
				{
					nimln(1335, "strutils.nim");
					invalidformatstring_123759();
				}
				break;
				}
			}
			goto LA3;
			LA5: ;
			{
				NI TMP359;
				nimln(1337, "strutils.nim");
				if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
				(*s) = addChar((*s), formatstr->data[i]);
				nimln(1338, "strutils.nim");
				TMP359 = addInt(i, ((NI) 1));
				i = (NI)(TMP359);
			}
			LA3: ;
		} LA2: ;
	}
	popFrame();
}

N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen0) {
	NimStringDesc* result;
	NI TMP333;
	nimfr("%", "strutils.nim")
	result = 0;
	nimln(1382, "strutils.nim");
	TMP333 = addInt((formatstr ? formatstr->Sup.len : 0), (NI)((NU32)(aLen0) << (NU32)(((NI) 4))));
	result = rawNewString(((NI)chckRange((NI)(TMP333), ((NI) 0), ((NI) 2147483647))));
	nimln(1383, "strutils.nim");
	nsuAddf((&result), formatstr, a, aLen0);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit)(void) {
	nimfr("strutils", "strutils.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit)(void) {
}

