/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -Ic:\Nim\lib -o c:\users\202378\documents\github\spacebarrace\src\nimcache\yup.o c:\users\202378\documents\github\spacebarrace\src\nimcache\yup.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>

#include <setjmp.h>

#include <stdio.h>
typedef struct SoundbufferHEX3Aobjecttype114447 SoundbufferHEX3Aobjecttype114447;
typedef struct SoundHEX3Aobjecttype114443 SoundHEX3Aobjecttype114443;
typedef struct RenderwindowHEX3Aobjecttype109634 RenderwindowHEX3Aobjecttype109634;
typedef struct Videomode107919 Videomode107919;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Contextsettings107943 Contextsettings107943;
typedef struct FontHEX3Aobjecttype109614 FontHEX3Aobjecttype109614;
typedef struct TextHEX3Aobjecttype109646 TextHEX3Aobjecttype109646;
typedef struct Color109438 Color109438;
typedef struct Vector2i106084 Vector2i106084;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TSafePoint TSafePoint;
typedef struct Event107892 Event107892;
typedef struct Keyevent107841 Keyevent107841;
typedef struct Mousebuttonevent107855 Mousebuttonevent107855;
typedef struct Textevent107848 Textevent107848;
typedef struct Joystickconnectevent107874 Joystickconnectevent107874;
typedef struct Joystickmoveevent107865 Joystickmoveevent107865;
typedef struct Joystickbuttonevent107870 Joystickbuttonevent107870;
typedef struct Sizeevent107877 Sizeevent107877;
typedef struct Mousemoveevent107851 Mousemoveevent107851;
typedef struct Mousewheelevent107860 Mousewheelevent107860;
typedef struct Renderstates110263 Renderstates110263;
typedef struct Blendmode109430 Blendmode109430;
typedef struct Transform109665 Transform109665;
typedef struct TextureHEX3Aobjecttype109650 TextureHEX3Aobjecttype109650;
typedef struct ShaderHEX3Aobjecttype109622 ShaderHEX3Aobjecttype109622;
typedef N_CDECL_PTR(SoundbufferHEX3Aobjecttype114447*, TY114636) (NCSTRING filename);
struct  Videomode107919  {
int width;
int height;
int bitsperpixel;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Contextsettings107943  {
int depthbits;
int stencilbits;
int antialiasinglevel;
int majorversion;
int minorversion;
};
typedef N_CDECL_PTR(FontHEX3Aobjecttype109614*, TY110022) (NCSTRING filename);
struct  Color109438  {
NU8 r;
NU8 g;
NU8 b;
NU8 a;
};
typedef N_CDECL_PTR(void, TY111161) (TextHEX3Aobjecttype109646* text, Color109438 color);
struct  Vector2i106084  {
int x;
int y;
};
typedef N_CDECL_PTR(int, TY110333) (RenderwindowHEX3Aobjecttype109634* renderwindow);
typedef NimStringDesc* TY138028[1];
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY15609;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY15609 raiseAction;
};
typedef N_CDECL_PTR(void, TY110418) (RenderwindowHEX3Aobjecttype109634* renderwindow, Color109438 color);
typedef NimStringDesc* TY138054[2];
typedef N_CDECL_PTR(Vector2i106084, TY110592) (RenderwindowHEX3Aobjecttype109634* relativeto);
struct  Keyevent107841  {
NI32 code;
int alt;
int control;
int shift;
int system;
};
struct  Mousebuttonevent107855  {
NI32 button;
int x;
int y;
};
struct  Textevent107848  {
NU32 unicode;
};
struct  Joystickconnectevent107874  {
int joystickid;
};
struct  Joystickmoveevent107865  {
int joystickid;
NI32 axis;
float position;
};
struct  Joystickbuttonevent107870  {
int joystickid;
int button;
};
struct  Sizeevent107877  {
int width;
int height;
};
struct  Mousemoveevent107851  {
int x;
int y;
};
struct  Mousewheelevent107860  {
int delta;
int x;
int y;
};
struct  Event107892  {
NI32 kind;
union{
struct {Keyevent107841 key;
} S1;
struct {Mousebuttonevent107855 mousebutton;
} S2;
struct {Textevent107848 text;
} S3;
struct {Joystickconnectevent107874 joystickconnect;
} S4;
struct {Joystickmoveevent107865 joystickmove;
} S5;
struct {Joystickbuttonevent107870 joystickbutton;
} S6;
struct {Sizeevent107877 size;
} S7;
struct {Mousemoveevent107851 mousemove;
} S8;
struct {Mousewheelevent107860 mousewheel;
} S9;
} kindU;
};
typedef N_CDECL_PTR(int, TY110339) (RenderwindowHEX3Aobjecttype109634* renderwindow, Event107892* event);
typedef N_CDECL_PTR(void, TY110330) (RenderwindowHEX3Aobjecttype109634* renderwindow);
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(void, TY114561) (SoundHEX3Aobjecttype114443* sound);
struct  Blendmode109430  {
NI32 colorsrcfactor;
NI32 colordstfactor;
NI32 colorequation;
NI32 alphasrcfactor;
NI32 alphadstfactor;
NI32 alphaequation;
};
typedef float TY109666[9];
struct  Transform109665  {
TY109666 matrix;
};
struct  Renderstates110263  {
Blendmode109430 blendmode;
Transform109665 transform;
TextureHEX3Aobjecttype109650* texture;
ShaderHEX3Aobjecttype109622* shader;
};
typedef N_CDECL_PTR(void, TY110404) (RenderwindowHEX3Aobjecttype109634* renderwindow);
typedef N_CDECL_PTR(void, TY111092) (TextHEX3Aobjecttype109646* text);
struct  SoundbufferHEX3Aobjecttype114447  {
char dummy;
};
struct  SoundHEX3Aobjecttype114443  {
char dummy;
};
struct  RenderwindowHEX3Aobjecttype109634  {
char dummy;
};
struct  FontHEX3Aobjecttype109614  {
char dummy;
};
struct  TextHEX3Aobjecttype109646  {
char dummy;
};
struct  TextureHEX3Aobjecttype109650  {
char dummy;
};
struct  ShaderHEX3Aobjecttype109622  {
char dummy;
};
N_NIMCALL(SoundHEX3Aobjecttype114443*, newsound_114758)(SoundbufferHEX3Aobjecttype114447* buffer);
N_NIMCALL(RenderwindowHEX3Aobjecttype109634*, newrenderwindow_112058)(Videomode107919 mode, NimStringDesc* title, NU32 style, Contextsettings107943 settings);
N_NIMCALL(Videomode107919, videomode_108140)(int modewidth, int modeheight, int bitsperpixel);
N_NIMCALL(NU32, tobitmasku32_108281)(NI32 a);
N_NIMCALL(Contextsettings107943, contextsettings_108099)(int depth, int stencil, int antialiasing, int major, int minor);
N_NIMCALL(TextHEX3Aobjecttype109646*, newtext_112474)(NimStringDesc* str, FontHEX3Aobjecttype109614* font, NI charactersize);
N_NIMCALL(NimStringDesc*, HEX24_138038)(Vector2i106084 x);
N_NIMCALL(NIM_BOOL, tobool_105085)(int x);
N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen0);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_NIMCALL(Color109438, color_111473)(NI red, NI green, NI blue, NI alpha);
N_NIMCALL(NI, random_136012)(NI max);
N_NIMCALL(void, write_13473)(FILE* f, NimStringDesc** a, NI aLen0);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
N_NIMCALL(NimStringDesc*, reprEnum)(NI e_84729, TNimType* typ);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NF, ntepochTime)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, draw_138106)(RenderwindowHEX3Aobjecttype109634* rendertarget, TextHEX3Aobjecttype109646* obj, Renderstates110263 states);
N_NIMCALL(Renderstates110263, renderstates_112012)(Blendmode109430 blendmode, Transform109665 transform, TextureHEX3Aobjecttype109650* texture, ShaderHEX3Aobjecttype109622* shader);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, reraiseException)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, csfml_csfml_utilInit)(void);
NIM_EXTERNC N_NOINLINE(void, csfml_csfml_utilDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, csfml_csfml_systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, csfml_csfml_systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, csfml_csfml_windowInit)(void);
NIM_EXTERNC N_NOINLINE(void, csfml_csfml_windowDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, csfml_csfml_graphicsInit)(void);
NIM_EXTERNC N_NOINLINE(void, csfml_csfml_graphicsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, csfml_csfmlInit)(void);
NIM_EXTERNC N_NOINLINE(void, csfml_csfmlDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, csfml_csfml_audioInit)(void);
NIM_EXTERNC N_NOINLINE(void, csfml_csfml_audioDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, yupInit)(void);
NIM_EXTERNC N_NOINLINE(void, yupDatInit)(void);
STRING_LITERAL(TMP326, "SpaceBar Race", 13);
STRING_LITERAL(TMP327, "        Press Space to Start", 28);
STRING_LITERAL(TMP328, "                   Game Over!", 29);
STRING_LITERAL(TMP360, "\015\012\015\012\015\012                          $1", 34);
STRING_LITERAL(TMP362, "\015\012\015\012\015\012      Your HighScore is $1 !", 34);
STRING_LITERAL(TMP364, "\015", 1);
STRING_LITERAL(TMP365, "key", 3);
STRING_LITERAL(TMP369, "Space", 5);
STRING_LITERAL(TMP371, "R", 1);
NI i_138007;
NIM_BOOL isbreak_138008;
NF timerstart_138009;
SoundbufferHEX3Aobjecttype114447* songfile_138014;
extern TY114636 Dl_114635;
SoundHEX3Aobjecttype114443* song_138015;
RenderwindowHEX3Aobjecttype109634* window_138018;
FontHEX3Aobjecttype109614* font_138019;
extern TY110022 Dl_110021;
TextHEX3Aobjecttype109646* text_138020;
TextHEX3Aobjecttype109646* go_138021;
extern TY111161 Dl_111160;
extern Color109438 Black_111639;
extern TY110333 Dl_110332;
extern TSafePoint* exchandler_17043;
extern TY110418 Dl_110417;
extern TY110592 Dl_110591;
extern TY110339 Dl_110338;
extern TY110330 Dl_110329;
extern TNimType NTI107667; /* KeyCode */
extern TY114561 Dl_114560;
extern Blendmode109430 Blendalpha_111959;
extern Transform109665 Identity_111808;
extern TY110404 Dl_110403;
extern TFrame* frameptr_17042;
extern TY111092 Dl_111091;

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = exchandler_17043;
	exchandler_17043 = s;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
{	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (*a).Sup.len);
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_17043 = (*exchandler_17043).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	frameptr_17042 = s;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit();
	stdlib_unicodeDatInit();
	stdlib_unsignedDatInit();
	csfml_csfml_utilDatInit();
	csfml_csfml_systemDatInit();
	csfml_csfml_windowDatInit();
	csfml_csfml_graphicsDatInit();
	csfml_csfmlDatInit();
	csfml_csfml_audioDatInit();
	stdlib_parseutilsDatInit();
	stdlib_strutilsDatInit();
	stdlib_winleanDatInit();
	stdlib_timesDatInit();
	stdlib_mathDatInit();
	yupDatInit();
	stdlib_unicodeInit();
	stdlib_unsignedInit();
	csfml_csfml_utilInit();
	csfml_csfml_systemInit();
	csfml_csfml_windowInit();
	csfml_csfml_graphicsInit();
	csfml_csfmlInit();
	csfml_csfml_audioInit();
	stdlib_parseutilsInit();
	stdlib_strutilsInit();
	stdlib_winleanInit();
	stdlib_timesInit();
	stdlib_mathInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	yupInit();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}


static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}
NIM_EXTERNC N_NOINLINE(void, yupInit)(void) {
	Videomode107919 LOC1;
	NU32 LOC2;
	Contextsettings107943 LOC3;
	nimfr("yup", "yup.nim")
	nimln(6, "yup.nim");
	i_138007 = ((NI) 0);
	nimln(7, "yup.nim");
	isbreak_138008 = NIM_FALSE;
	nimln(11, "yup.nim");
	songfile_138014 = Dl_114635("imports/Et.wav");
	nimln(12, "yup.nim");
	song_138015 = newsound_114758(songfile_138014);
	nimln(13, "yup.nim");
	LOC1 = videomode_108140(((int) 400), ((int) 200), ((int) 32));
	nimln(235, "csfml_graphics.nim");
	LOC2 = 0;
	LOC2 = tobitmasku32_108281(((NI32) 7));
	nimln(236, "csfml_graphics.nim");
	LOC3 = contextsettings_108099(((int) 0), ((int) 0), ((int) 0), ((int) 2), ((int) 0));
	window_138018 = newrenderwindow_112058(LOC1, ((NimStringDesc*) &TMP326), LOC2, LOC3);
	nimln(14, "yup.nim");
	font_138019 = Dl_110021("imports/sansation.ttf");
	nimln(15, "yup.nim");
	text_138020 = newtext_112474(((NimStringDesc*) &TMP327), font_138019, ((NI) 30));
	nimln(16, "yup.nim");
	go_138021 = newtext_112474(((NimStringDesc*) &TMP328), font_138019, ((NI) 30));
	nimln(18, "yup.nim");
	Dl_111160(text_138020, Black_111639);
	{
		nimln(20, "yup.nim");
		while (1) {
			int LOC6;
			NIM_BOOL LOC7;
			TextHEX3Aobjecttype109646* count;
			TY138028 LOC8;
			NimStringDesc* LOC9;
			TSafePoint TMP361;
			LOC6 = 0;
			LOC6 = Dl_110332(window_138018);
			LOC7 = 0;
			LOC7 = tobool_105085(LOC6);
			if (!LOC7) goto LA5;
			nimln(21, "yup.nim");
			nimln(25, "yup.nim");
			memset((void*)LOC8, 0, sizeof(LOC8));
			LOC8[0] = nimIntToStr(i_138007);
			LOC9 = 0;
			LOC9 = nsuFormatOpenArray(((NimStringDesc*) &TMP360), LOC8, 1);
			count = newtext_112474(LOC9, font_138019, ((NI) 30));
			nimln(21, "yup.nim");
			pushSafePoint(&TMP361);
			TMP361.status = setjmp(TMP361.context);
			if (TMP361.status == 0) {
				TextHEX3Aobjecttype109646* e;
				TY138028 LOC11;
				NimStringDesc* LOC12;
				TSafePoint TMP363;
				nimln(26, "yup.nim");
				nimln(30, "yup.nim");
				memset((void*)LOC11, 0, sizeof(LOC11));
				LOC11[0] = nimIntToStr(i_138007);
				LOC12 = 0;
				LOC12 = nsuFormatOpenArray(((NimStringDesc*) &TMP362), LOC11, 1);
				e = newtext_112474(LOC12, font_138019, ((NI) 30));
				nimln(26, "yup.nim");
				pushSafePoint(&TMP363);
				TMP363.status = setjmp(TMP363.context);
				if (TMP363.status == 0) {
					NI LOC14;
					NI LOC15;
					NI LOC16;
					Color109438 LOC17;
					TY138054 LOC18;
					Vector2i106084 LOC19;
					Event107892 event;
					nimln(31, "yup.nim");
					Dl_111160(count, Black_111639);
					nimln(32, "yup.nim");
					LOC14 = 0;
					LOC14 = random_136012(((NI) 255));
					LOC15 = 0;
					LOC15 = random_136012(((NI) 255));
					LOC16 = 0;
					LOC16 = random_136012(((NI) 255));
					LOC17 = color_111473(LOC14, LOC15, LOC16, ((NI) 255));
					Dl_110417(window_138018, LOC17);
					nimln(33, "yup.nim");
					memset((void*)LOC18, 0, sizeof(LOC18));
					LOC19 = Dl_110591(window_138018);
					LOC18[0] = HEX24_138038(LOC19);
					LOC18[1] = copyString(((NimStringDesc*) &TMP364));
					write_13473(stdout, LOC18, 2);
					memset((void*)(&event), 0, sizeof(event));
					{
						{
							nimln(36, "yup.nim");
							while (1) {
								int LOC23;
								NIM_BOOL LOC24;
								LOC23 = 0;
								LOC23 = Dl_110338(window_138018, (&event));
								LOC24 = 0;
								LOC24 = tobool_105085(LOC23);
								if (!LOC24) goto LA22;
								nimln(37, "yup.nim");
								{
									if (!(event.kind == ((NI32) 0))) goto LA27;
									nimln(38, "yup.nim");
									Dl_110329(window_138018);
								}
								goto LA25;
								LA27: ;
								{
									nimln(39, "yup.nim");
									if (!(event.kind == ((NI32) 5))) goto LA30;
									nimln(40, "yup.nim");
									{
										NI TMP370;
										if (!(((96 &(1<<((event.kind)&31)))!=0))) raiseFieldError(((NimStringDesc*) &TMP365));
										if (!eqStrings(reprEnum(event.kindU.S1.key.code, (&NTI107667)), ((NimStringDesc*) &TMP369))) goto LA34;
										nimln(41, "yup.nim");
										{
											if (!(i_138007 < ((NI) 1))) goto LA38;
											nimln(42, "yup.nim");
											timerstart_138009 = ntepochTime();
											nimln(43, "yup.nim");
											Dl_114560(song_138015);
										}
										LA38: ;
										nimln(44, "yup.nim");
										{
											NF LOC42;
											LOC42 = 0;
											LOC42 = ntepochTime();
											if (!(1.0000000000000000e+001 <= ((NF)(LOC42) - (NF)(timerstart_138009)))) goto LA43;
											nimln(45, "yup.nim");
											isbreak_138008 = NIM_TRUE;
											nimln(46, "yup.nim");
											goto LA20;
										}
										LA43: ;
										nimln(47, "yup.nim");
										TMP370 = addInt(i_138007, ((NI) 1));
										i_138007 = (NI)(TMP370);
									}
									goto LA32;
									LA34: ;
									{
										nimln(48, "yup.nim");
										if (!(((96 &(1<<((event.kind)&31)))!=0))) raiseFieldError(((NimStringDesc*) &TMP365));
										if (!eqStrings(reprEnum(event.kindU.S1.key.code, (&NTI107667)), ((NimStringDesc*) &TMP371))) goto LA46;
										nimln(49, "yup.nim");
										timerstart_138009 = ntepochTime();
										nimln(50, "yup.nim");
										isbreak_138008 = NIM_FALSE;
										nimln(51, "yup.nim");
										i_138007 = ((NI) 0);
									}
									goto LA32;
									LA46: ;
									LA32: ;
								}
								goto LA25;
								LA30: ;
								LA25: ;
							} LA22: ;
						}
					} LA20: ;
					nimln(54, "yup.nim");
					{
						Renderstates110263 LOC52;
						Renderstates110263 LOC53;
						if (!isbreak_138008) goto LA50;
						nimln(55, "yup.nim");
						nimln(279, "csfml_graphics.nim");
						LOC52 = renderstates_112012(Blendalpha_111959, Identity_111808, NIM_NIL, NIM_NIL);
						draw_138106(window_138018, e, LOC52);
						nimln(56, "yup.nim");
						nimln(279, "csfml_graphics.nim");
						LOC53 = renderstates_112012(Blendalpha_111959, Identity_111808, NIM_NIL, NIM_NIL);
						draw_138106(window_138018, go_138021, LOC53);
					}
					goto LA48;
					LA50: ;
					{
						Renderstates110263 LOC55;
						Renderstates110263 LOC56;
						nimln(58, "yup.nim");
						nimln(279, "csfml_graphics.nim");
						LOC55 = renderstates_112012(Blendalpha_111959, Identity_111808, NIM_NIL, NIM_NIL);
						draw_138106(window_138018, count, LOC55);
						nimln(59, "yup.nim");
						nimln(279, "csfml_graphics.nim");
						LOC56 = renderstates_112012(Blendalpha_111959, Identity_111808, NIM_NIL, NIM_NIL);
						draw_138106(window_138018, text_138020, LOC56);
					}
					LA48: ;
					nimln(60, "yup.nim");
					Dl_110403(window_138018);
					popSafePoint();
				}
				else {
					popSafePoint();
					setFrame((TFrame*)&FR);
				}
				{
					nimln(26, "yup.nim");
					Dl_111091(e);
				}
				if (TMP363.status != 0) reraiseException();
				popSafePoint();
			}
			else {
				popSafePoint();
				setFrame((TFrame*)&FR);
			}
			{
				nimln(21, "yup.nim");
				Dl_111091(count);
			}
			if (TMP361.status != 0) reraiseException();
		} LA5: ;
	}
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, yupDatInit)(void) {
}

